### PR TITLE
CORE-406 implement UI changes for SEPA

### PR DESCRIPTION
**Pull request by karladler**
small UI fixes according to CORE-406

### CODE REVIEW

**Comment by Tschuck** [comment]
All changes are made correctly.

I found one unknown issue according to country switch and VAT validation. By switching from germany to another country, the VAT will be flagged correctly as required but the form validation isn't triggered again, so i can submit the form without validation. By switching from another country to germany, the same issue occures.

profile eve-payment

**Comment by Tschuck** [comment]
By switching to light theme, the Credit Card Number will not be readable.

profile eve-payment light theme

**Review by Tschuck — COMMENTED** [review]
- please have a look at the conversation

**Comment by karladler** [comment]
> By switching to light theme, the Credit Card Number will not be readable.
> 
> profile eve-payment light theme

there is a light theme?! 🤯

**Review by Tschuck — APPROVED** [review]

**Pull request merged**
